version: "2"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=caderosche@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart: always

  deno-app:
    image: cprosche/deno-app:latest
    environment:
      - VIRTUAL_HOST=theunitseo.com,www.theunitseo.com
      - LETSENCRYPT_HOST=theunitseo.com,www.theunitseo.com
    network_mode: bridge
    restart: always

# step 1: 
# docker run --detach --name nginx-proxy --publish 80:80 --publish 443:443 --volume certs:/etc/nginx/certs --volume vhost:/etc/nginx/vhost.d --volume html:/usr/share/nginx/html --volume /var/run/docker.sock:/tmp/docker.sock:ro nginxproxy/nginx-proxy

# step 2: 
# docker run --detach --name nginx-proxy-acme --volumes-from nginx-proxy --volume /var/run/docker.sock:/var/run/docker.sock:ro --volume acme:/etc/acme.sh --env "DEFAULT_EMAIL=mail@yourdomain.tld" nginxproxy/acme-companion

# step 3: 
# docker run --detach --name deno-app --env "VIRTUAL_HOST=testing.caderosche.com" --env "LETSENCRYPT_HOST=testing.caderosche.com" cprosche/deno-app:latest