version: "3.9"
services:
  nginx-proxy: 
    image: "nginxproxy/nginx-proxy"
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-proxy-acme: 
    image: nginxproxy/acme-companion
    volumes: 
      - nginx-proxy:/var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=caderosche@gmail.com
  deno-app:
    image: cprosche/deno-app:latest
    environment:
      - VIRTUAL_HOST=theunitseo.com,www.theunitseo.com
      - LETSENCRYPT_HOST=theunitseo.com,www.theunitseo.com